-- AlterTable
ALTER TABLE "teacher_info" ADD COLUMN "academic_title_attestat" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "academic_title_name" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "academic_title_speciality" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "academic_title_year" INTEGER;
ALTER TABLE "teacher_info" ADD COLUMN "awards_field" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "awards_state" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "bachelor_diploma_number" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "bachelor_direction" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "bachelor_university" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "bachelor_year" INTEGER;
ALTER TABLE "teacher_info" ADD COLUMN "conferences_international" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "conferences_republic" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_country" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_diploma_number" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_organization" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_speciality" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_topic" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "dsc_year" INTEGER;
ALTER TABLE "teacher_info" ADD COLUMN "has_academic_title" BOOLEAN DEFAULT false;
ALTER TABLE "teacher_info" ADD COLUMN "has_dsc_degree" BOOLEAN DEFAULT false;
ALTER TABLE "teacher_info" ADD COLUMN "has_phd_degree" BOOLEAN DEFAULT false;
ALTER TABLE "teacher_info" ADD COLUMN "innovative_ideas_count" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "internships_count" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "internships_info" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "master_diploma_number" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "master_direction" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "master_university" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "master_year" INTEGER;
ALTER TABLE "teacher_info" ADD COLUMN "phd_country" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "phd_diploma_number" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "phd_organization" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "phd_speciality" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "phd_topic" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "phd_year" INTEGER;
ALTER TABLE "teacher_info" ADD COLUMN "projects_business" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "projects_fundamental" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "projects_innovation" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "projects_practical" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "projects_youth" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "research_area" TEXT;
ALTER TABLE "teacher_info" ADD COLUMN "seminars_international" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "seminars_republic" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "supervised_dsc" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "supervised_phd" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "training_count" INTEGER DEFAULT 0;
ALTER TABLE "teacher_info" ADD COLUMN "training_info" TEXT;

-- AlterTable
ALTER TABLE "user_info" ADD COLUMN "country_of_birth" TEXT;
ALTER TABLE "user_info" ADD COLUMN "current_address" TEXT;
ALTER TABLE "user_info" ADD COLUMN "date_of_birth" DATETIME;
ALTER TABLE "user_info" ADD COLUMN "english_level" TEXT;
ALTER TABLE "user_info" ADD COLUMN "gender" TEXT;
ALTER TABLE "user_info" ADD COLUMN "middle_name" TEXT;
ALTER TABLE "user_info" ADD COLUMN "nationality" TEXT;
ALTER TABLE "user_info" ADD COLUMN "passport_serial" TEXT;
ALTER TABLE "user_info" ADD COLUMN "permanent_address" TEXT;
ALTER TABLE "user_info" ADD COLUMN "personal_id" TEXT;
ALTER TABLE "user_info" ADD COLUMN "profile_image" TEXT;
ALTER TABLE "user_info" ADD COLUMN "region_of_birth" TEXT;
ALTER TABLE "user_info" ADD COLUMN "stir_inn" TEXT;
